### ISSUE TITLE
get 'Use of unresolved identifier' when calling BProgressHUD.showLoadingView()

### ISSUE THREAD

**Issue by ghost** [chinabrant/BProgressHUD#1]
I've just installed the utility using cocoapods and when calling BProgressHUD.showLoadingView() am getting that error.

Am I doing something wrong?

**Comment by chinabrant** [comment]
what identifier?

**Comment by ghost** [comment]
'BProgressHUD', even after doing the import.

In the end I've opened the BProgress class on the module and then made public the class and the methods.

**Comment by ghost** [comment]
so is closed because I was doing something wrong? or is this an expected behavior?
